### ISSUE TITLE
Where is the proposed specification located?

### ISSUE THREAD

**Issue by JakeChampion** [w3c/system-wake-lock#1]
I just learnt about the split of wake lock into the two separate features: screen wake lock and system wake lock.

Screen Wake Lock looks to have a specification written -- https://w3c.github.io/screen-wake-lock/
System Wake Lock does not -- https://w3c.github.io/system-wake-lock/

I also can't find any open issues or discussions about system wake lock.

Is there anything written down for System Wake Lock that I can have a read of?

**Comment by reillyeon** [comment]
This repository is a placeholder for a future System Wake Lock specification. The last discussion on this was in w3c/screen-wake-lock#232. It is yet to be decided at this point whether a System Wake Lock will look like it did when it was combined with Screen Wake Lock or if a different design approach will be taken.

At this point in the design process it would be most helpful to collect use cases for System Wake Lock so that these can inform the design.

**Comment by anssiko** [comment]
See also the [snapshot](https://rawcdn.githack.com/w3c/screen-wake-lock/543bd1070b77a051dbc3f58eab43dbff178d4256/index.html) of the spec before the split that includes the system wake lock. This is based on commit https://github.com/w3c/screen-wake-lock/commit/543bd1070b77a051dbc3f58eab43dbff178d4256 from Feb 5, 2020.

You can find old system wake lock discussions from the screen-wake-lock repo that is the old (combined) wake-lock repo but renamed: https://github.com/w3c/screen-wake-lock/issues?q=is%3Aissue+system

**Comment by JakeChampion** [comment]
Thank you so much for your help locating the spec and previous discussions

**Comment by CheloXL** [comment]
@reillyeon Where should we inform use cases? I already have an app that could possible make use of it (based on what it may look like from the previous discussions).

**Comment by reillyeon** [comment]
Please create a new issue which describes your use case with the summary prefix "Use case: " so we can track them.
